services:
  mlops-iris-api:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    #deploy:
    #  replicas: 3
    container_name: mlops-iris-api
    expose:
      - "8000"

  nginx:
    build:
      context: deployments/nginx/
      dockerfile: Dockerfile
    container_name: nginx_revproxy
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./deployments/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deployments/nginx/certs:/etc/nginx/certs:ro
      - ./deployments/nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - mlops-iris-api

  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:latest
    command:
      - "-nginx.scrape-uri=http://nginx_revproxy/nginx_status"
    ports:
      - "9113:9113"
    depends_on:
      - nginx

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./deployments/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - nginx_exporter

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
