services:  # <--- COLUMN 1 (No spaces)
  mlops-iris-api: # <--- Indented 2 spaces  
    build: # <--- Indented 4 spaces
      context: .
      dockerfile: src/api/Dockerfile
    deploy:
      replicas: 3
    expose:
      - "8000"

  nginx: # <--- Indented 2 spaces (MUST align exactly with 'mlops-iris-api')
    build: # <--- Indented 4 spaces
      context: deployments/nginx/
      dockerfile: Dockerfile
    container_name: nginx_revproxy
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./deployments/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deployments/nginx/certs:/etc/nginx/certs:ro
      - ./deployments/nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - mlops-iris-api
